server:
  port: 8090

spring:
  application:
    name: gateway-server
  profiles:
    active: dev

  redis:
    host: 192.168.3.12
    port: 6379
    password: 123456
    database: 0

  cloud:
    nacos:
      server-addr: 192.168.3.12:8848
      discovery:
        group: store-dev-group
    gateway:
      routes:
        #订单服务
        - id: order-server
          uri: lb://order-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/order-server/api/**
          filters:
            - StripPrefix=2
        #用户服务
        - id: user-server
          uri: lb://user-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/user-server/api/**
          filters:
            - StripPrefix=2
        #认证服务
        - id: auth-server-id
          uri: lb://auth-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/auth-server/api/**
          filters:
            - StripPrefix=2
        #商场服务
        - id: store-server-id
          uri: lb://store-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/store-server/api/**
          #对下游服务发起请求前去掉 /store-server/api
          filters:
            - StripPrefix=2
        #通用服务
        - id: utilities-server-id
          uri: lb://utilities-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/utilities/api/**
          filters:
            - StripPrefix=2
  #提供自定义HTML模板
#  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML
#    encoding: utf-8
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}


