server:
  port: 8082

spring:
  application:
    name: user-server
  profiles:
    active: '@active@'

  redis:
    host: ${account.ali}
    port: 6379
    password: ${account.redis.password}
    database: 0

  cloud:
    nacos:
      server-addr: ${account.ali}:8848
      discovery:
        group: store-dev-group

  datasource:
    url: jdbc:mysql://${account.ali}:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${account.mysql.username}
    password: ${account.mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: ENC(auQU1fISSOZgrQGkACJo1XGNi+w5Prm9):9200
      connection-timeout: 3

#日志配置
logging:
  config: classpath:logback-spring.xml

#rocketmq配置
rocketmq:
  name-server: ${account.tx}
  producer:
    group: store-user-dev-producer
    send-message-timeout: 3000
  consumer:
    group: store-user-dev-comsumer


jasypt:
  encryptor:
    password: store-2022



account:
  tx: ENC(auQU1fISSOZgrQGkACJo1XGNi+w5Prm9)
  ali: ENC(yeM6Qsmg92+HorSl1w4RAaFhC98koe2z)
  redis:
    password: ENC(R8bnGKQ0yJL+9XF3KjANzA==)
  mysql:
    username: ENC(pOVHRpzPR5n9Bd/MJ3IIAw==)
    password: ENC(vSnGLlMnQEgn6+vc6LsZGbNyqe7aGaAb)

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.userserver.**.entity,com.fqh.userserver.**.request,com.fqh.userserver.**.response
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delete_mark
      logic-delete-value: 1
      logic-not-delete-value: 0
