server:
  port: 8082

spring:
  application:
    name: user-server
  profiles:
    active: @ative@

  redis:
    host: 47.106.211.14
    port: 6379
    password: 123456
    database: 0

  cloud:
    nacos:
      server-addr: 47.106.211.14

