server:
  port: 8099
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-server
  profiles:
    active: local
  thymeleaf:
    enabled: true
    cache: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES # 加密算法
    password: ${JASYPT_PWD} # 使用加密密钥
