server:
  port: 8081

spring:
  application:
    name: auth-server
  profiles:
    active: '@active@'

  redis:
    host: ${account.ali}
    port: 6379
    password: ${account.redis.password}
    database: 0

  cloud:
    nacos:
      server-addr: ${account.ali}:8848
      discovery:
        group: store-dev-group
    gateway:
      routes:
        - id: order-server
          uri: lb://order-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/gateway/order-server/**
          filters:
            - StripPrefix=2

        - id: user-server
          uri: lb://user-server
          #满足断言 跳转到uri地址
          predicates:
            - Path=/gateway/user-server/**
          filters:
            - StripPrefix=2
  #提供自定义HTML模板
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
account:
  tx: ENC(auQU1fISSOZgrQGkACJo1XGNi+w5Prm9)
  ali: ENC(yeM6Qsmg92+HorSl1w4RAaFhC98koe2z)
  redis:
    password: ENC(R8bnGKQ0yJL+9XF3KjANzA==)
  mysql:
    username: ENC(pOVHRpzPR5n9Bd/MJ3IIAw==)
    password: ENC(vSnGLlMnQEgn6+vc6LsZGbNyqe7aGaAb)