spring:
#  redis:
#    host: ${service.ip}
#    port: 6379
#    password: ENC(0G0O4JG9E1tX2ZGv7W6/sw==)
#    database: 0

  datasource:
    url: jdbc:mysql://${service.ip}:3306/db_auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fqh@mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.auth.**.entity,com.fqh.auth.**.request,com.fqh.auth.**.response
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delete_mark
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  secret: fqh@2024
  expireTime: 2
service:
  ip: localhost
