spring:
  datasource:
    url: jdbc:mysql://${service.ip}:3306/utilities_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ENC(GMHJ/ZuKhpEpbsgk7wSQEA==)
    password: ENC(jjVz5RkxRj342uPW+MwGCuUkflOWfi0f)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10240000

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.utilities.**.entity,com.fqh.utilities.**.request,com.fqh.utilities.**.response
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delete_mark
      logic-delete-value: 1
      logic-not-delete-value: 0
#日志配置
logging:
  config: classpath:logback-spring.xml

upload:
  path: /opt/upload

service:
  ip: ENC(WjMkadU7o28ArViLBLO0uMBxSbfh5L0S)