store-host: localhost

spring:
  redis:
    host: ${store-host}
    port: 6379
    password: 123456
    database: 0
  datasource:
    url: jdbc:mysql://${store-host}:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  #mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.storeserver.**.entity,com.fqh.storeserver.**.request,com.fqh.storeserver.**.response
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delete_mark
      logic-delete-value: 1
      logic-not-delete-value: 0
  #rocketmq配置
  #rocketmq:
  #  name-server: ${account.tx}
  #  producer:
  #    group: store-user-dev-producer
  #    send-message-timeout: 3000
  #  consumer:
  #    group: store-user-dev-comsumer
