server:
  port: 8084

spring:
  application:
    name: order-server

  redis:
    host: 47.106.211.14
    port: 6379
    password: 123456
    database: 0

  cloud:
    nacos:
      server-addr: 47.106.211.14
      discovery:
        group: store-dev-group

  datasource:
    url: jdbc:mysql://47.106.211.14:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: store_2021071
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


