server:
  port: 8084

spring:
  application:
    name: order-server

  redis:
    host: ${account.ali}
    port: 6379
    password: ${account.redis.password}
    database: 0

  cloud:
    nacos:
      server-addr: ${account.ali}
      discovery:
        group: store-dev-group

  datasource:
    url: jdbc:mysql://ENC(yeM6Qsmg92+HorSl1w4RAaFhC98koe2z):3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${account.mysql.username}
    password: ${account.mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: ENC(auQU1fISSOZgrQGkACJo1XGNi+w5Prm9):9200
      connection-timeout: 3

#日志配置
logging:
  config: classpath:logback-spring.xml

#rocketmq配置
rocketmq:
  name-server: ${account.tx}
  producer:
    group: store-order-dev-producer
    send-message-timeout: 3000
  consumer:
    group: store-order-dev-comsumer


jasypt:
  encryptor:
    password: store-2022



account:
  tx: ENC(auQU1fISSOZgrQGkACJo1XGNi+w5Prm9)
  ali: ENC(yeM6Qsmg92+HorSl1w4RAaFhC98koe2z)
  redis:
    password: ENC(R8bnGKQ0yJL+9XF3KjANzA==)
  mysql:
    username: ENC(pOVHRpzPR5n9Bd/MJ3IIAw==)
    password: ENC(vSnGLlMnQEgn6+vc6LsZGbNyqe7aGaAb)

